# Copyright (c) 2026 BOSC & ICT, CAS
# All rights reserved.
# See LICENSE for license details.
CASE_BINARY := test_llm_gemm_mixed
CASE_DESCRIPTION := INT8 x INT8 to INT32 widening GEMM (N=128)
REQUIRED_MNEMONICS := mls.rm mss.rm mmulacc.2d
include ../common/case_rules.mk
