# Copyright (c) 2026 BOSC & ICT, CAS
# All rights reserved.
# See LICENSE for license details.
CASE_BINARY := test_llm_gemm_int8
CASE_DESCRIPTION := INT8 GEMM with conversion (N=128)
REQUIRED_MNEMONICS := mls.rm mss.rm mmulacc.2d mconv.ew
include ../common/case_rules.mk
