#!/usr/bin/env python3
#
# Copyright (c) 2026 BOSC & ICT, CAS
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

"""Write per-case and aggregate Markdown reports for the Makefile runner."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def display_name(name: str) -> str:
    return name.removeprefix("test_llm_")


def parse_blocks(path: Path) -> list[tuple[int, str, str]]:
    text = path.read_text(encoding="utf-8")
    matches = list(re.finditer(r"(?m)^case\[(\d+)\]: (.+)\n", text))
    blocks = []
    for index, match in enumerate(matches):
        if index + 1 < len(matches):
            end = matches[index + 1].start()
        else:
            end = len(text)
        blocks.append(
            (int(match.group(1)), match.group(2), text[match.start():end])
        )
    return blocks


def write_case(args: argparse.Namespace) -> None:
    golden_blocks = parse_blocks(args.golden)
    spike_blocks = parse_blocks(args.spike)
    spike_by_index = {
        index: (name, block) for index, name, block in spike_blocks
    }
    rows = []
    all_equal = args.golden.read_bytes() == args.spike.read_bytes()
    for index, name, golden_block in golden_blocks:
        spike = spike_by_index.get(index)
        equal = spike is not None and spike == (name, golden_block)
        rows.append(
            f"| {index + 1} | `{name}` | PASS | PASS | "
            f"{'PASS' if spike else 'FAIL'} | "
            f"{'PASS' if equal else 'FAIL'} |"
        )
    lines = [
        f"# `{args.name}` Example Report",
        "",
        f"{args.description} from `{args.source}`.",
        "",
        "| # | Operator case | Instruction audit | "
        f"{args.golden_label} | Spike | Comparison |",
        "| ---: | --- | --- | --- | --- | --- |",
        *rows,
        "",
        f"Overall report comparison: **{'PASS' if all_equal else 'FAIL'}**.",
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    result = "PASS" if all_equal else "FAIL"
    print(f"[RESULT] {display_name(args.name)}: {result}")


def write_suite(args: argparse.Namespace) -> None:
    lines = [
        "# AMEspike Example Report",
        "",
        "Generated by `make test` using AMEspike/Spike. "
        "No SHA validation is used.",
        "",
    ]
    results = []
    for report in args.reports:
        text = report.read_text(encoding="utf-8")
        lines.append(text.replace("# `", "## `", 1).rstrip())
        lines.append("")
        title = re.search(r"(?m)^# `([^`]+)` Example Report", text)
        overall = re.search(
            r"Overall report comparison: \*\*(PASS|FAIL)\*\*", text
        )
        results.append(
            (
                title.group(1) if title else report.parent.parent.name,
                overall.group(1) if overall else "FAIL",
            )
        )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    passed = sum(result == "PASS" for _, result in results)
    total = len(results)
    overall = "PASS" if passed == total else "FAIL"
    print(
        f"[RESULT] example suite: {overall} "
        f"({passed}/{total} cases passed)"
    )
    for name, result in results:
        print(f"         {result}: {display_name(name)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    case = subparsers.add_parser("case")
    case.add_argument("--name", required=True)
    case.add_argument("--description", required=True)
    case.add_argument("--source", required=True)
    case.add_argument("--golden", required=True, type=Path)
    case.add_argument("--golden-label", required=True)
    case.add_argument("--spike", required=True, type=Path)
    case.add_argument("--output", required=True, type=Path)
    case.set_defaults(function=write_case)

    suite = subparsers.add_parser("suite")
    suite.add_argument("--output", required=True, type=Path)
    suite.add_argument("reports", nargs="+", type=Path)
    suite.set_defaults(function=write_suite)

    args = parser.parse_args()
    args.function(args)


if __name__ == "__main__":
    main()
