// Copyright (c) 2026 BOSC & ICT, CAS
// All rights reserved.
// See LICENSE for license details.

#ifndef _RISCV_ZTT_EXECUTE_H
#define _RISCV_ZTT_EXECUTE_H

#include "decode.h"

enum class ztt_opcode_t : unsigned {
  ame_acquire,
  ame_release,
  agettyp,
  asettyp,
  mabs_ew,
  mabsdiff_ew,
  mabsdiff_ew_x,
  madd_ew,
  madd_ew_x,
  mand_ew,
  mand_ew_x,
  mandnot_ew,
  mandnot_ew_x,
  mcmovge_ew,
  mcmovlt_ew,
  mcmpge_ew,
  mcmpge_ew_x,
  mcmplt_ew,
  mcmplt_ew_x,
  mcolbcast_ew_x,
  mcolgather_ew,
  mcolid_ew,
  mcolshift_ew_x,
  mcolunzip_ew,
  mcolzip_ew,
  mconv_ew,
  mbcast_m_x,
  mcos_ew,
  mexp2_ew,
  mfrintm_ew,
  mfrintn_ew,
  mfrintp_ew,
  mfrintz_ew,
  mgettyp,
  mhdiff_ew,
  mhdiff_ew_x,
  mldexp_ew,
  mldexp_ew_x,
  mldexpacc_ew,
  mldexpacc_ew_x,
  mlog2_ew,
  mlog2sub_ew,
  mlog2sub_ew_x,
  mls_1r,
  mls_cm,
  mls_rm,
  mls_st,
  mls_tst,
  mmax_ew,
  mmax_ew_x,
  mmean_ew,
  mmean_ew_x,
  mmin_ew,
  mmin_ew_x,
  mmov_m_a,
  mmov_a_m,
  mmov_m_m,
  mmove8_m_x,
  mmove16_m_x,
  mmove32_m_x,
  mmove64_m_x,
  mmove8_x_m,
  mmove16_x_m,
  mmove32_x_m,
  mmove64_x_m,
  mmul_ew,
  mmul_ew_x,
  mmulacc_2d,
  mmulacc_ew,
  mmulacc_ew_x,
  mmulaccneg_2d,
  mmulaccneg_ew,
  mmulaccneg_ew_x,
  mmuladd_ew,
  mmuladd_ew_x,
  mmulatacc_2d,
  mmulataccneg_2d,
  mmulbtacc_2d,
  mmulbtaccneg_2d,
  mmulneg_ew,
  mmulneg_ew_x,
  mmulsub_ew,
  mmulsub_ew_x,
  mor_ew,
  mor_ew_x,
  mornot_ew,
  mornot_ew_x,
  mpack_ew_x,
  mprefixadd_col,
  mprefixadd_row,
  mprefixmax_col,
  mprefixmax_row,
  mrdexp_ew,
  mrdexpacc_ew,
  mrec_ew,
  mreduceadd_col,
  mreduceadd_row,
  mreducemax_col,
  mreducemax_row,
  mreducemin_col,
  mreducemin_row,
  mrowbcast_ew_x,
  mrowgather_ew,
  mrowid_ew,
  mrowshift_ew_x,
  mrowunzip_ew,
  mrowzip_ew,
  mrsqrt_ew,
  mrowscatadd_ew,
  mcolscatadd_ew,
  mrowscatmax_ew,
  mcolscatmax_ew,
  mselge_ew,
  msellt_ew,
  msettyp,
  msin_ew,
  msll_ew,
  msll_ew_x,
  msqrt_ew,
  msra_ew,
  msra_ew_x,
  msrl_ew,
  msrl_ew_x,
  mss_1r,
  mss_cm,
  mss_rm,
  mss_st,
  mss_tst,
  msub_ew,
  msub_ew_x,
  msublog2_ew,
  msublog2_ew_x,
  mtanh_ew,
  munpack_ew_x,
  mxor_ew,
  mxor_ew_x,
  mzero_2d_acc,
  mzero_2d_m,
};

class processor_t;
bool ztt_opcode_may_modify_state(ztt_opcode_t opcode);
void execute_ztt(processor_t& proc, ztt_opcode_t opcode, insn_t insn);

#endif
