// Copyright (c) 2026 BOSC & ICT, CAS
// All rights reserved.
// See LICENSE for license details.

#include "decode.h"
#include "encoding.h"
#include <array>
#include <cassert>
#include <cstddef>

namespace {
struct encoding_t { insn_bits_t match; insn_bits_t mask; };
constexpr std::array<encoding_t, 138> ztt_encodings = {{
  {MATCH_ZTT_AME_ACQUIRE, MASK_ZTT_AME_ACQUIRE},
  {MATCH_ZTT_AME_RELEASE, MASK_ZTT_AME_RELEASE},
  {MATCH_ZTT_AGETTYP, MASK_ZTT_AGETTYP},
  {MATCH_ZTT_ASETTYP, MASK_ZTT_ASETTYP},
  {MATCH_ZTT_MABS_EW, MASK_ZTT_MABS_EW},
  {MATCH_ZTT_MABSDIFF_EW, MASK_ZTT_MABSDIFF_EW},
  {MATCH_ZTT_MABSDIFF_EW_X, MASK_ZTT_MABSDIFF_EW_X},
  {MATCH_ZTT_MADD_EW, MASK_ZTT_MADD_EW},
  {MATCH_ZTT_MADD_EW_X, MASK_ZTT_MADD_EW_X},
  {MATCH_ZTT_MAND_EW, MASK_ZTT_MAND_EW},
  {MATCH_ZTT_MAND_EW_X, MASK_ZTT_MAND_EW_X},
  {MATCH_ZTT_MANDNOT_EW, MASK_ZTT_MANDNOT_EW},
  {MATCH_ZTT_MANDNOT_EW_X, MASK_ZTT_MANDNOT_EW_X},
  {MATCH_ZTT_MCMOVGE_EW, MASK_ZTT_MCMOVGE_EW},
  {MATCH_ZTT_MCMOVLT_EW, MASK_ZTT_MCMOVLT_EW},
  {MATCH_ZTT_MCMPGE_EW, MASK_ZTT_MCMPGE_EW},
  {MATCH_ZTT_MCMPGE_EW_X, MASK_ZTT_MCMPGE_EW_X},
  {MATCH_ZTT_MCMPLT_EW, MASK_ZTT_MCMPLT_EW},
  {MATCH_ZTT_MCMPLT_EW_X, MASK_ZTT_MCMPLT_EW_X},
  {MATCH_ZTT_MCOLBCAST_EW_X, MASK_ZTT_MCOLBCAST_EW_X},
  {MATCH_ZTT_MCOLGATHER_EW, MASK_ZTT_MCOLGATHER_EW},
  {MATCH_ZTT_MCOLID_EW, MASK_ZTT_MCOLID_EW},
  {MATCH_ZTT_MCOLSHIFT_EW_X, MASK_ZTT_MCOLSHIFT_EW_X},
  {MATCH_ZTT_MCOLUNZIP_EW, MASK_ZTT_MCOLUNZIP_EW},
  {MATCH_ZTT_MCOLZIP_EW, MASK_ZTT_MCOLZIP_EW},
  {MATCH_ZTT_MCONV_EW, MASK_ZTT_MCONV_EW},
  {MATCH_ZTT_MBCAST_M_X, MASK_ZTT_MBCAST_M_X},
  {MATCH_ZTT_MCOS_EW, MASK_ZTT_MCOS_EW},
  {MATCH_ZTT_MEXP2_EW, MASK_ZTT_MEXP2_EW},
  {MATCH_ZTT_MFRINTM_EW, MASK_ZTT_MFRINTM_EW},
  {MATCH_ZTT_MFRINTN_EW, MASK_ZTT_MFRINTN_EW},
  {MATCH_ZTT_MFRINTP_EW, MASK_ZTT_MFRINTP_EW},
  {MATCH_ZTT_MFRINTZ_EW, MASK_ZTT_MFRINTZ_EW},
  {MATCH_ZTT_MGETTYP, MASK_ZTT_MGETTYP},
  {MATCH_ZTT_MHDIFF_EW, MASK_ZTT_MHDIFF_EW},
  {MATCH_ZTT_MHDIFF_EW_X, MASK_ZTT_MHDIFF_EW_X},
  {MATCH_ZTT_MLDEXP_EW, MASK_ZTT_MLDEXP_EW},
  {MATCH_ZTT_MLDEXP_EW_X, MASK_ZTT_MLDEXP_EW_X},
  {MATCH_ZTT_MLDEXPACC_EW, MASK_ZTT_MLDEXPACC_EW},
  {MATCH_ZTT_MLDEXPACC_EW_X, MASK_ZTT_MLDEXPACC_EW_X},
  {MATCH_ZTT_MLOG2_EW, MASK_ZTT_MLOG2_EW},
  {MATCH_ZTT_MLOG2SUB_EW, MASK_ZTT_MLOG2SUB_EW},
  {MATCH_ZTT_MLOG2SUB_EW_X, MASK_ZTT_MLOG2SUB_EW_X},
  {MATCH_ZTT_MLS_1R, MASK_ZTT_MLS_1R},
  {MATCH_ZTT_MLS_CM, MASK_ZTT_MLS_CM},
  {MATCH_ZTT_MLS_RM, MASK_ZTT_MLS_RM},
  {MATCH_ZTT_MLS_ST, MASK_ZTT_MLS_ST},
  {MATCH_ZTT_MLS_TST, MASK_ZTT_MLS_TST},
  {MATCH_ZTT_MMAX_EW, MASK_ZTT_MMAX_EW},
  {MATCH_ZTT_MMAX_EW_X, MASK_ZTT_MMAX_EW_X},
  {MATCH_ZTT_MMEAN_EW, MASK_ZTT_MMEAN_EW},
  {MATCH_ZTT_MMEAN_EW_X, MASK_ZTT_MMEAN_EW_X},
  {MATCH_ZTT_MMIN_EW, MASK_ZTT_MMIN_EW},
  {MATCH_ZTT_MMIN_EW_X, MASK_ZTT_MMIN_EW_X},
  {MATCH_ZTT_MMOV_M_A, MASK_ZTT_MMOV_M_A},
  {MATCH_ZTT_MMOV_A_M, MASK_ZTT_MMOV_A_M},
  {MATCH_ZTT_MMOV_M_M, MASK_ZTT_MMOV_M_M},
  {MATCH_ZTT_MMOVE8_M_X, MASK_ZTT_MMOVE8_M_X},
  {MATCH_ZTT_MMOVE16_M_X, MASK_ZTT_MMOVE16_M_X},
  {MATCH_ZTT_MMOVE32_M_X, MASK_ZTT_MMOVE32_M_X},
  {MATCH_ZTT_MMOVE64_M_X, MASK_ZTT_MMOVE64_M_X},
  {MATCH_ZTT_MMOVE8_X_M, MASK_ZTT_MMOVE8_X_M},
  {MATCH_ZTT_MMOVE16_X_M, MASK_ZTT_MMOVE16_X_M},
  {MATCH_ZTT_MMOVE32_X_M, MASK_ZTT_MMOVE32_X_M},
  {MATCH_ZTT_MMOVE64_X_M, MASK_ZTT_MMOVE64_X_M},
  {MATCH_ZTT_MMUL_EW, MASK_ZTT_MMUL_EW},
  {MATCH_ZTT_MMUL_EW_X, MASK_ZTT_MMUL_EW_X},
  {MATCH_ZTT_MMULACC_2D, MASK_ZTT_MMULACC_2D},
  {MATCH_ZTT_MMULACC_EW, MASK_ZTT_MMULACC_EW},
  {MATCH_ZTT_MMULACC_EW_X, MASK_ZTT_MMULACC_EW_X},
  {MATCH_ZTT_MMULACCNEG_2D, MASK_ZTT_MMULACCNEG_2D},
  {MATCH_ZTT_MMULACCNEG_EW, MASK_ZTT_MMULACCNEG_EW},
  {MATCH_ZTT_MMULACCNEG_EW_X, MASK_ZTT_MMULACCNEG_EW_X},
  {MATCH_ZTT_MMULADD_EW, MASK_ZTT_MMULADD_EW},
  {MATCH_ZTT_MMULADD_EW_X, MASK_ZTT_MMULADD_EW_X},
  {MATCH_ZTT_MMULATACC_2D, MASK_ZTT_MMULATACC_2D},
  {MATCH_ZTT_MMULATACCNEG_2D, MASK_ZTT_MMULATACCNEG_2D},
  {MATCH_ZTT_MMULBTACC_2D, MASK_ZTT_MMULBTACC_2D},
  {MATCH_ZTT_MMULBTACCNEG_2D, MASK_ZTT_MMULBTACCNEG_2D},
  {MATCH_ZTT_MMULNEG_EW, MASK_ZTT_MMULNEG_EW},
  {MATCH_ZTT_MMULNEG_EW_X, MASK_ZTT_MMULNEG_EW_X},
  {MATCH_ZTT_MMULSUB_EW, MASK_ZTT_MMULSUB_EW},
  {MATCH_ZTT_MMULSUB_EW_X, MASK_ZTT_MMULSUB_EW_X},
  {MATCH_ZTT_MOR_EW, MASK_ZTT_MOR_EW},
  {MATCH_ZTT_MOR_EW_X, MASK_ZTT_MOR_EW_X},
  {MATCH_ZTT_MORNOT_EW, MASK_ZTT_MORNOT_EW},
  {MATCH_ZTT_MORNOT_EW_X, MASK_ZTT_MORNOT_EW_X},
  {MATCH_ZTT_MPACK_EW_X, MASK_ZTT_MPACK_EW_X},
  {MATCH_ZTT_MPREFIXADD_COL, MASK_ZTT_MPREFIXADD_COL},
  {MATCH_ZTT_MPREFIXADD_ROW, MASK_ZTT_MPREFIXADD_ROW},
  {MATCH_ZTT_MPREFIXMAX_COL, MASK_ZTT_MPREFIXMAX_COL},
  {MATCH_ZTT_MPREFIXMAX_ROW, MASK_ZTT_MPREFIXMAX_ROW},
  {MATCH_ZTT_MRDEXP_EW, MASK_ZTT_MRDEXP_EW},
  {MATCH_ZTT_MRDEXPACC_EW, MASK_ZTT_MRDEXPACC_EW},
  {MATCH_ZTT_MREC_EW, MASK_ZTT_MREC_EW},
  {MATCH_ZTT_MREDUCEADD_COL, MASK_ZTT_MREDUCEADD_COL},
  {MATCH_ZTT_MREDUCEADD_ROW, MASK_ZTT_MREDUCEADD_ROW},
  {MATCH_ZTT_MREDUCEMAX_COL, MASK_ZTT_MREDUCEMAX_COL},
  {MATCH_ZTT_MREDUCEMAX_ROW, MASK_ZTT_MREDUCEMAX_ROW},
  {MATCH_ZTT_MREDUCEMIN_COL, MASK_ZTT_MREDUCEMIN_COL},
  {MATCH_ZTT_MREDUCEMIN_ROW, MASK_ZTT_MREDUCEMIN_ROW},
  {MATCH_ZTT_MROWBCAST_EW_X, MASK_ZTT_MROWBCAST_EW_X},
  {MATCH_ZTT_MROWGATHER_EW, MASK_ZTT_MROWGATHER_EW},
  {MATCH_ZTT_MROWID_EW, MASK_ZTT_MROWID_EW},
  {MATCH_ZTT_MROWSHIFT_EW_X, MASK_ZTT_MROWSHIFT_EW_X},
  {MATCH_ZTT_MROWUNZIP_EW, MASK_ZTT_MROWUNZIP_EW},
  {MATCH_ZTT_MROWZIP_EW, MASK_ZTT_MROWZIP_EW},
  {MATCH_ZTT_MRSQRT_EW, MASK_ZTT_MRSQRT_EW},
  {MATCH_ZTT_MROWSCATADD_EW, MASK_ZTT_MROWSCATADD_EW},
  {MATCH_ZTT_MCOLSCATADD_EW, MASK_ZTT_MCOLSCATADD_EW},
  {MATCH_ZTT_MROWSCATMAX_EW, MASK_ZTT_MROWSCATMAX_EW},
  {MATCH_ZTT_MCOLSCATMAX_EW, MASK_ZTT_MCOLSCATMAX_EW},
  {MATCH_ZTT_MSELGE_EW, MASK_ZTT_MSELGE_EW},
  {MATCH_ZTT_MSELLT_EW, MASK_ZTT_MSELLT_EW},
  {MATCH_ZTT_MSETTYP, MASK_ZTT_MSETTYP},
  {MATCH_ZTT_MSIN_EW, MASK_ZTT_MSIN_EW},
  {MATCH_ZTT_MSLL_EW, MASK_ZTT_MSLL_EW},
  {MATCH_ZTT_MSLL_EW_X, MASK_ZTT_MSLL_EW_X},
  {MATCH_ZTT_MSQRT_EW, MASK_ZTT_MSQRT_EW},
  {MATCH_ZTT_MSRA_EW, MASK_ZTT_MSRA_EW},
  {MATCH_ZTT_MSRA_EW_X, MASK_ZTT_MSRA_EW_X},
  {MATCH_ZTT_MSRL_EW, MASK_ZTT_MSRL_EW},
  {MATCH_ZTT_MSRL_EW_X, MASK_ZTT_MSRL_EW_X},
  {MATCH_ZTT_MSS_1R, MASK_ZTT_MSS_1R},
  {MATCH_ZTT_MSS_CM, MASK_ZTT_MSS_CM},
  {MATCH_ZTT_MSS_RM, MASK_ZTT_MSS_RM},
  {MATCH_ZTT_MSS_ST, MASK_ZTT_MSS_ST},
  {MATCH_ZTT_MSS_TST, MASK_ZTT_MSS_TST},
  {MATCH_ZTT_MSUB_EW, MASK_ZTT_MSUB_EW},
  {MATCH_ZTT_MSUB_EW_X, MASK_ZTT_MSUB_EW_X},
  {MATCH_ZTT_MSUBLOG2_EW, MASK_ZTT_MSUBLOG2_EW},
  {MATCH_ZTT_MSUBLOG2_EW_X, MASK_ZTT_MSUBLOG2_EW_X},
  {MATCH_ZTT_MTANH_EW, MASK_ZTT_MTANH_EW},
  {MATCH_ZTT_MUNPACK_EW_X, MASK_ZTT_MUNPACK_EW_X},
  {MATCH_ZTT_MXOR_EW, MASK_ZTT_MXOR_EW},
  {MATCH_ZTT_MXOR_EW_X, MASK_ZTT_MXOR_EW_X},
  {MATCH_ZTT_MZERO_2D_ACC, MASK_ZTT_MZERO_2D_ACC},
  {MATCH_ZTT_MZERO_2D_M, MASK_ZTT_MZERO_2D_M},
}};
bool overlaps(const encoding_t& a, const encoding_t& b)
{
  return ((a.match ^ b.match) & a.mask & b.mask) == 0;
}
} // namespace

int main()
{
  for (const auto& encoding : ztt_encodings)
    assert((encoding.match & encoding.mask) == encoding.match);
  for (std::size_t i = 0; i < ztt_encodings.size(); ++i)
    for (std::size_t j = i + 1; j < ztt_encodings.size(); ++j)
      assert(!overlaps(ztt_encodings[i], ztt_encodings[j]));

  static_assert(MATCH_ZTT_AME_ACQUIRE == 0xa490002b);
  static_assert(MATCH_ZTT_AME_RELEASE == 0xa4a0002b);
  static_assert(MATCH_ZTT_MADD_EW == 0x0400002b);
  static_assert(MATCH_ZTT_MMULACC_2D == 0x9400002b);
  static_assert(MATCH_ZTT_MPACK_EW_X == 0x7a00002b);
  static_assert(MATCH_ZTT_MUNPACK_EW_X == 0x7c00002b);
  static_assert(MATCH_ZTT_MZERO_2D_ACC == 0xa600002b);

  // Zip/unzip operands occupy rs1 and rs2; rd is reserved as zero.
  static_assert(MASK_ZTT_MCOLUNZIP_EW == 0xfe007fff);
  static_assert(MASK_ZTT_MCOLZIP_EW == 0xfe007fff);
  static_assert(MASK_ZTT_MROWUNZIP_EW == 0xfe007fff);
  static_assert(MASK_ZTT_MROWZIP_EW == 0xfe007fff);
  static_assert((0xc283002b & MASK_ZTT_MCOLUNZIP_EW) == MATCH_ZTT_MCOLUNZIP_EW);
  static_assert((0xc483002b & MASK_ZTT_MCOLZIP_EW) == MATCH_ZTT_MCOLZIP_EW);
  static_assert((0xc683002b & MASK_ZTT_MROWUNZIP_EW) == MATCH_ZTT_MROWUNZIP_EW);
  static_assert((0x7083002b & MASK_ZTT_MROWZIP_EW) == MATCH_ZTT_MROWZIP_EW);
  static_assert((0xc28300ab & MASK_ZTT_MCOLUNZIP_EW) != MATCH_ZTT_MCOLUNZIP_EW);
  return 0;
}
